version: "3.7"
services:
  app:
    container_name: app
    build:
      context: .
      dockerfile: Dockerfile
    platform: linux/amd64
    volumes:
      - ./express:/app
      - /app/node_modules
      - /app/build
    ports:
      - 3001:3001
  frontend:
    container_name: frontend
    build:
      context: ./react
      dockerfile: Dockerfile
    volumes:
      - ./react:/app
      - /app/node_modules
    ports:
      - 3000:3000
    environment:
      CHOKIDAR_USEPOLLING: 'true'
      NODE_ENV: 'development'