name: NodeJS build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]

    steps:
    - uses: actions/checkout@v4

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}

    - name: Build
      run: |
        cd react
        npm i
        npm run build
        mv -f ./build ../express/build

    - name: Commit changes
      run: |
        git config --global user.name 'Johnathan'
        git config --global user.email 'wong.johnathanwh@gmail.com'
        git add .
        git commit -m "Update React build files and copy to Express build directory"
        git push origin main --force-with-lease

